resources:
- https://github.com/metallb/frr-k8s/config/default/?timeout=120&ref=v0.0.18
images:
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: registry.k8s.io/kubebuilder/kube-rbac-proxy
patches:
- path: loglevel-patch.yaml
  target:
    kind: DaemonSet
    name: frr-k8s-daemon
