version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
  - package-ecosystem: "gomod"
    directory: "/e2etests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
  - package-ecosystem: "gomod"
    directory: "/website"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
