apiVersion: network.openperouter.io/v1alpha1
kind: L3VNI
metadata:
  name: red
  namespace: openperouter-system
spec:
  vni: 100
  vrf: red
---
apiVersion: network.openperouter.io/v1alpha1
kind: L2VNI
metadata:
  name: layer2
  namespace: openperouter-system
spec:
  hostmaster:
    type: linux-bridge
    linuxBridge:
      autoCreate: true
  gatewayIPs: ["192.170.1.1/24"]
  vni: 110
  routingDomain:
    type: L3VNI
    l3vni:
      name: red
---
apiVersion: network.openperouter.io/v1alpha1
kind: Underlay
metadata:
  name: underlay
  namespace: openperouter-system
spec:
  asn: 64514
  tunnelEndpoint:
    cidrs:
    - 100.65.0.0/24
  interfaces:
    - type: NetworkDevice
      networkDevice:
        interfaceName: toswitch1
  neighbors:
    - asn: 64512
      address: 192.168.11.2
