apiVersion: network.openperouter.io/v1alpha1
kind: L2VNI
metadata:
  name: migration-net
  namespace: openperouter-system
spec:
  hostmaster:
    type: linux-bridge
    linuxBridge:
      autoCreate: true
  gatewayIPs: ["192.170.10.1/24"]
  vni: 666
  routingDomain:
    type: L3VNI
    l3vni:
      name: rouge
