---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-openperouter-io-v1alpha1-l2vni
  failurePolicy: Fail
  name: l2vnivalidationwebhook.openperouter.io
  rules:
  - apiGroups:
    - openpe.openperouter.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - l2vnis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-openperouter-io-v1alpha1-l3passthrough
  failurePolicy: Fail
  name: l3passthroughvalidationwebhook.openperouter.io
  rules:
  - apiGroups:
    - openpe.openperouter.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - l3passthroughs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-openperouter-io-v1alpha1-l3vni
  failurePolicy: Fail
  name: l3vnivalidationwebhook.openperouter.io
  rules:
  - apiGroups:
    - openpe.openperouter.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - l3vnis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-openperouter-io-v1alpha1-rawfrrconfig
  failurePolicy: Fail
  name: rawfrrconfigvalidationwebhook.openperouter.io
  rules:
  - apiGroups:
    - openpe.openperouter.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rawfrrconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-openperouter-io-v1alpha1-underlay
  failurePolicy: Fail
  name: underlayvalidationwebhook.openperouter.io
  rules:
  - apiGroups:
    - openpe.openperouter.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - underlays
  sideEffects: None
