log file /etc/frr/frr.log debug

debug zebra events
debug zebra vxlan
debug zebra nht
debug zebra kernel
debug zebra rib
debug zebra nexthop
debug bgp neighbor-events
debug bgp updates
debug bgp keepalives
debug bgp nht
debug bgp zebra
debug bfd network
debug bfd peer
debug bfd zebra

router bgp 64513
 no bgp ebgp-requires-policy
 no bgp network import-check
 no bgp default ipv4-unicast

 neighbor 192.168.1.6 remote-as 64612

 neighbor kind-nodes peer-group
 neighbor kind-nodes remote-as 64514

 bgp listen range 192.168.12.0/24 peer-group kind-nodes
 bgp listen range 2001:db8:12::/64 peer-group kind-nodes

 !
 address-family ipv4 unicast
  neighbor kind-nodes activate
  neighbor 192.168.1.6 activate
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor kind-nodes activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 192.168.1.6 activate
  neighbor kind-nodes activate
  advertise-all-vni
  advertise-svi-ip
 exit-address-family
exit
!
router isis ISIS
  is-type level-1
  advertise-passive-only
  net 49.0001.0000.0000.0005.00
exit
!
interface eth1
  ipv6 router isis ISIS
exit
!
interface toswitch2
  ipv6 router isis ISIS
exit
