frr version 10.6.0_git
frr defaults traditional
hostname leafkind1
log file /etc/frr/frr.log
!
debug zebra events
debug zebra kernel
debug zebra rib
debug zebra nht
debug zebra vxlan
debug zebra nexthop
debug bgp keepalives
debug bgp neighbor-events
debug bgp nht
debug bgp updates in
debug bgp updates out
debug bgp zebra
debug bgp graceful-restart
debug bfd peer
debug bfd zebra
debug bfd network
!
interface eth1
 ipv6 router isis ISIS
exit
!
interface toswitch1
 ipv6 router isis ISIS
exit
!
router bgp 64512
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp graceful-restart
 bgp graceful-restart preserve-fw-state
 no bgp network import-check
 neighbor 192.168.1.4 remote-as 64612
 neighbor 2001:db8:11::3 remote-as 64514
 neighbor 2001:db8:11::3 timers connect 5
 neighbor 2001:db8:11::4 remote-as 64514
 neighbor 2001:db8:11::4 timers connect 5
 neighbor 2001:db8:11::5 remote-as 64514
 neighbor 2001:db8:11::5 timers connect 5
 !
 address-family ipv4 unicast
  neighbor 192.168.1.4 activate
  neighbor 2001:db8:11::3 activate
  neighbor 2001:db8:11::4 activate
  neighbor 2001:db8:11::5 activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 192.168.1.4 activate
  neighbor 2001:db8:11::3 activate
  neighbor 2001:db8:11::4 activate
  neighbor 2001:db8:11::5 activate
  advertise-all-vni
  advertise-svi-ip
 exit-address-family
exit
!
router isis ISIS
 is-type level-1
 net 49.0001.0000.0000.0004.00
 advertise-passive-only
exit
!
