ARG OPM_IMAGE=registry.redhat.io/openshift4/ose-operator-registry-rhel9:v5.0

FROM ${OPM_IMAGE}

# ensure this correponds to olm.package name
ENV PACKAGE_NAME=openperouter-operator
COPY .konflux/catalog/$PACKAGE_NAME/ /configs/$PACKAGE_NAME

RUN ["/bin/opm", "serve", "/configs", "--cache-dir=/tmp/cache", "--cache-only"]

ENTRYPOINT ["/bin/opm"]
CMD ["serve", "/configs", "--cache-dir=/tmp/cache"]

LABEL operators.operatorframework.io.index.configs.v1=/configs
