# L2VNI for worker nodes only
apiVersion: network.openperouter.io/v1alpha1
kind: L2VNI
metadata:
  name: app-network
  namespace: openperouter-system
spec:
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker: ""
  vni: 10100
  vxlanport: 4789
  routingDomain:
    type: L3VNI
    l3vni:
      name: app-l3vni
  hostmaster:
    type: linux-bridge
    linuxBridge:
      autoCreate: true
  gatewayIPs:
    - 10.100.0.1/24

