apiVersion: network.openperouter.io/v1alpha1
kind: L2VNI
metadata:
  name: l2red
  namespace: openperouter-system
spec:
  vni: 210
  routingDomain:
    type: L3VNI
    l3vni:
      name: red
  hostmaster:
    type: linux-bridge
    linuxBridge:
      autoCreate: true


