//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BFDSettings) DeepCopyInto(out *BFDSettings) {
	*out = *in
	if in.ReceiveInterval != nil {
		in, out := &in.ReceiveInterval, &out.ReceiveInterval
		*out = new(uint32)
		**out = **in
	}
	if in.TransmitInterval != nil {
		in, out := &in.TransmitInterval, &out.TransmitInterval
		*out = new(uint32)
		**out = **in
	}
	if in.DetectMultiplier != nil {
		in, out := &in.DetectMultiplier, &out.DetectMultiplier
		*out = new(uint32)
		**out = **in
	}
	if in.EchoInterval != nil {
		in, out := &in.EchoInterval, &out.EchoInterval
		*out = new(uint32)
		**out = **in
	}
	if in.EchoMode != nil {
		in, out := &in.EchoMode, &out.EchoMode
		*out = new(bool)
		**out = **in
	}
	if in.PassiveMode != nil {
		in, out := &in.PassiveMode, &out.PassiveMode
		*out = new(bool)
		**out = **in
	}
	if in.MinimumTTL != nil {
		in, out := &in.MinimumTTL, &out.MinimumTTL
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BFDSettings.
func (in *BFDSettings) DeepCopy() *BFDSettings {
	if in == nil {
		return nil
	}
	out := new(BFDSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EVPNConfig) DeepCopyInto(out *EVPNConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EVPNConfig.
func (in *EVPNConfig) DeepCopy() *EVPNConfig {
	if in == nil {
		return nil
	}
	out := new(EVPNConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostMaster) DeepCopyInto(out *HostMaster) {
	*out = *in
	if in.LinuxBridge != nil {
		in, out := &in.LinuxBridge, &out.LinuxBridge
		*out = new(LinuxBridgeConfig)
		**out = **in
	}
	if in.OVSBridge != nil {
		in, out := &in.OVSBridge, &out.OVSBridge
		*out = new(OVSBridgeConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostMaster.
func (in *HostMaster) DeepCopy() *HostMaster {
	if in == nil {
		return nil
	}
	out := new(HostMaster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostSession) DeepCopyInto(out *HostSession) {
	*out = *in
	out.LocalCIDR = in.LocalCIDR
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostSession.
func (in *HostSession) DeepCopy() *HostSession {
	if in == nil {
		return nil
	}
	out := new(HostSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2VNI) DeepCopyInto(out *L2VNI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2VNI.
func (in *L2VNI) DeepCopy() *L2VNI {
	if in == nil {
		return nil
	}
	out := new(L2VNI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L2VNI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2VNIList) DeepCopyInto(out *L2VNIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]L2VNI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2VNIList.
func (in *L2VNIList) DeepCopy() *L2VNIList {
	if in == nil {
		return nil
	}
	out := new(L2VNIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L2VNIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2VNISpec) DeepCopyInto(out *L2VNISpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.VRF != nil {
		in, out := &in.VRF, &out.VRF
		*out = new(string)
		**out = **in
	}
	if in.HostMaster != nil {
		in, out := &in.HostMaster, &out.HostMaster
		*out = new(HostMaster)
		(*in).DeepCopyInto(*out)
	}
	if in.L2GatewayIPs != nil {
		in, out := &in.L2GatewayIPs, &out.L2GatewayIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2VNISpec.
func (in *L2VNISpec) DeepCopy() *L2VNISpec {
	if in == nil {
		return nil
	}
	out := new(L2VNISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2VNIStatus) DeepCopyInto(out *L2VNIStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2VNIStatus.
func (in *L2VNIStatus) DeepCopy() *L2VNIStatus {
	if in == nil {
		return nil
	}
	out := new(L2VNIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3Passthrough) DeepCopyInto(out *L3Passthrough) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3Passthrough.
func (in *L3Passthrough) DeepCopy() *L3Passthrough {
	if in == nil {
		return nil
	}
	out := new(L3Passthrough)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L3Passthrough) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3PassthroughList) DeepCopyInto(out *L3PassthroughList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]L3Passthrough, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3PassthroughList.
func (in *L3PassthroughList) DeepCopy() *L3PassthroughList {
	if in == nil {
		return nil
	}
	out := new(L3PassthroughList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L3PassthroughList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3PassthroughSpec) DeepCopyInto(out *L3PassthroughSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.HostSession = in.HostSession
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3PassthroughSpec.
func (in *L3PassthroughSpec) DeepCopy() *L3PassthroughSpec {
	if in == nil {
		return nil
	}
	out := new(L3PassthroughSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3PassthroughStatus) DeepCopyInto(out *L3PassthroughStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3PassthroughStatus.
func (in *L3PassthroughStatus) DeepCopy() *L3PassthroughStatus {
	if in == nil {
		return nil
	}
	out := new(L3PassthroughStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3VNI) DeepCopyInto(out *L3VNI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3VNI.
func (in *L3VNI) DeepCopy() *L3VNI {
	if in == nil {
		return nil
	}
	out := new(L3VNI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L3VNI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3VNIList) DeepCopyInto(out *L3VNIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]L3VNI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3VNIList.
func (in *L3VNIList) DeepCopy() *L3VNIList {
	if in == nil {
		return nil
	}
	out := new(L3VNIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L3VNIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3VNISpec) DeepCopyInto(out *L3VNISpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.HostSession != nil {
		in, out := &in.HostSession, &out.HostSession
		*out = new(HostSession)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3VNISpec.
func (in *L3VNISpec) DeepCopy() *L3VNISpec {
	if in == nil {
		return nil
	}
	out := new(L3VNISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3VNIStatus) DeepCopyInto(out *L3VNIStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3VNIStatus.
func (in *L3VNIStatus) DeepCopy() *L3VNIStatus {
	if in == nil {
		return nil
	}
	out := new(L3VNIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinuxBridgeConfig) DeepCopyInto(out *LinuxBridgeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinuxBridgeConfig.
func (in *LinuxBridgeConfig) DeepCopy() *LinuxBridgeConfig {
	if in == nil {
		return nil
	}
	out := new(LinuxBridgeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalCIDRConfig) DeepCopyInto(out *LocalCIDRConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalCIDRConfig.
func (in *LocalCIDRConfig) DeepCopy() *LocalCIDRConfig {
	if in == nil {
		return nil
	}
	out := new(LocalCIDRConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Neighbor) DeepCopyInto(out *Neighbor) {
	*out = *in
	if in.HostASN != nil {
		in, out := &in.HostASN, &out.HostASN
		*out = new(uint32)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(uint16)
		**out = **in
	}
	if in.HoldTime != nil {
		in, out := &in.HoldTime, &out.HoldTime
		*out = new(v1.Duration)
		**out = **in
	}
	if in.KeepaliveTime != nil {
		in, out := &in.KeepaliveTime, &out.KeepaliveTime
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ConnectTime != nil {
		in, out := &in.ConnectTime, &out.ConnectTime
		*out = new(v1.Duration)
		**out = **in
	}
	if in.BFD != nil {
		in, out := &in.BFD, &out.BFD
		*out = new(BFDSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Neighbor.
func (in *Neighbor) DeepCopy() *Neighbor {
	if in == nil {
		return nil
	}
	out := new(Neighbor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVSBridgeConfig) DeepCopyInto(out *OVSBridgeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVSBridgeConfig.
func (in *OVSBridgeConfig) DeepCopy() *OVSBridgeConfig {
	if in == nil {
		return nil
	}
	out := new(OVSBridgeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawFRRConfig) DeepCopyInto(out *RawFRRConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawFRRConfig.
func (in *RawFRRConfig) DeepCopy() *RawFRRConfig {
	if in == nil {
		return nil
	}
	out := new(RawFRRConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RawFRRConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawFRRConfigList) DeepCopyInto(out *RawFRRConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RawFRRConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawFRRConfigList.
func (in *RawFRRConfigList) DeepCopy() *RawFRRConfigList {
	if in == nil {
		return nil
	}
	out := new(RawFRRConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RawFRRConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawFRRConfigSpec) DeepCopyInto(out *RawFRRConfigSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawFRRConfigSpec.
func (in *RawFRRConfigSpec) DeepCopy() *RawFRRConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RawFRRConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawFRRConfigStatus) DeepCopyInto(out *RawFRRConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawFRRConfigStatus.
func (in *RawFRRConfigStatus) DeepCopy() *RawFRRConfigStatus {
	if in == nil {
		return nil
	}
	out := new(RawFRRConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Underlay) DeepCopyInto(out *Underlay) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Underlay.
func (in *Underlay) DeepCopy() *Underlay {
	if in == nil {
		return nil
	}
	out := new(Underlay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Underlay) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnderlayList) DeepCopyInto(out *UnderlayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Underlay, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnderlayList.
func (in *UnderlayList) DeepCopy() *UnderlayList {
	if in == nil {
		return nil
	}
	out := new(UnderlayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnderlayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnderlaySpec) DeepCopyInto(out *UnderlaySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Neighbors != nil {
		in, out := &in.Neighbors, &out.Neighbors
		*out = make([]Neighbor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Nics != nil {
		in, out := &in.Nics, &out.Nics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EVPN != nil {
		in, out := &in.EVPN, &out.EVPN
		*out = new(EVPNConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnderlaySpec.
func (in *UnderlaySpec) DeepCopy() *UnderlaySpec {
	if in == nil {
		return nil
	}
	out := new(UnderlaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnderlayStatus) DeepCopyInto(out *UnderlayStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnderlayStatus.
func (in *UnderlayStatus) DeepCopy() *UnderlayStatus {
	if in == nil {
		return nil
	}
	out := new(UnderlayStatus)
	in.DeepCopyInto(out)
	return out
}
