frr version 10.6
frr defaults traditional
hostname tor-qemu
log stdout informational
service integrated-vtysh-config
!
ip route 0.0.0.0/0 192.168.100.254
!
interface eth0
 ip router isis QEMU
 ipv6 router isis QEMU
 isis circuit-type level-1
exit
!
interface lo
 ipv6 router isis QEMU
 isis passive
exit
!
router isis QEMU
 is-type level-1
 net 49.0001.0000.0000.0001.00
 segment-routing srv6
  locator MAIN
 exit
exit
!
segment-routing
 srv6
  encapsulation
   source-address 2001:db8:1234::1
  exit
  locators
   locator MAIN
    prefix fd00:0:10::/48 block-len 32 node-len 16
    behavior usid
    format usid-f3216
   exit
  exit
 exit
exit
!
vrf red
 vni 100
 ip route 192.168.20.0/24 Null0
 ipv6 route 2001:db8:20::/64 Null0
exit-vrf
!
vrf blue
 vni 200
 ip route 192.168.21.0/24 Null0
 ipv6 route 2001:db8:21::/64 Null0
exit-vrf
!
router bgp 65000
 bgp router-id 100.64.0.1
 no bgp ebgp-requires-policy
 no bgp network import-check
 no bgp default ipv4-unicast
 !
 neighbor 192.168.100.10 remote-as external
 !
 segment-routing srv6
  locator MAIN
 exit
 !
 address-family ipv4 unicast
  neighbor 192.168.100.10 activate
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor 192.168.100.10 activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 192.168.100.10 activate
  advertise-all-vni
 exit-address-family
 !
 address-family ipv4 vpn
  neighbor 192.168.100.10 activate
 exit-address-family
 !
 address-family ipv6 vpn
  neighbor 192.168.100.10 activate
 exit-address-family
exit
!
router bgp 65000 vrf red
 bgp router-id 100.64.0.1
 sid vpn per-vrf export auto
 !
 address-family ipv4 unicast
  redistribute static
  rd vpn export 100.64.0.1:100
  rt vpn both 65000:100 64514:100
  export vpn
  import vpn
 exit-address-family
 !
 address-family ipv6 unicast
  redistribute static
  rd vpn export 100.64.0.1:100
  rt vpn both 65000:100 64514:100
  export vpn
  import vpn
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  advertise ipv6 unicast
 exit-address-family
exit
!
router bgp 65000 vrf blue
 bgp router-id 100.64.0.1
 sid vpn per-vrf export auto
 !
 address-family ipv4 unicast
  redistribute static
  rd vpn export 100.64.0.1:200
  rt vpn both 65000:200 64514:200
  export vpn
  import vpn
 exit-address-family
 !
 address-family ipv6 unicast
  redistribute static
  rd vpn export 100.64.0.1:200
  rt vpn both 65000:200 64514:200
  export vpn
  import vpn
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  advertise ipv6 unicast
 exit-address-family
exit
!
line vty
!
