frr version 10.6
frr defaults traditional
hostname tor-qemu
log stdout informational

ip route 0.0.0.0/0 192.168.100.254

router bgp 65000
 no bgp ebgp-requires-policy
 no bgp network import-check
 no bgp default ipv4-unicast
 neighbor 192.168.100.10 remote-as 64514

 address-family ipv4 unicast
  neighbor 192.168.100.10 activate
 exit-address-family

 address-family l2vpn evpn
  neighbor 192.168.100.10 activate
  advertise-all-vni
 exit-address-family
exit

line vty
