name: Verify Website

on:
  pull_request:
    paths:
      - 'website/**'
      - 'api/**'
      - 'hack/crd-ref-docs.yaml'
    branches:
      - "main"
      - "v**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-website:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Build website
        run: make build-website
